config/routes.rb
Rails.application.routes.draw do

  devise_for :networks, :consultants, :companies, :admins

  scope '/admin' do
    resources :companies, :consultants, :networks
  end

  get 'admins/index'

  get 'consultants/profile'

  get 'networks/profile'

  get 'companies/profile'

  root to: 'index#index'

end

app/models/consultant.rb
class Consultant
  include Mongoid::Document
  include Mongoid::Timestamps
  
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  belongs_to :network
  has_and_belongs_to_many :companies
  has_many :companies_consultants

  field :name,              type: String, default: ""

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/consultants_controller.rb
class ConsultantsController < ApplicationController
  layout "admin", except: [:profile]

  before_action :authenticate_consultant!, only: [:profile]
  before_action :authenticate_admin!, except: [:profile]
  before_action :set_consultant, only: [:show, :edit, :update, :destroy]

  # GET /consultants
  # GET /consultants.json
  def index
    @consultants = Consultant.all
  end

  # GET /consultants/1
  # GET /consultants/1.json
  def show
  end

  # GET /consultants/new
  def new
    @consultant = Consultant.new
    @companies = Company.all
  end

  # GET /consultants/1/edit
  def edit
  end

  # GET /consultants/profile
  def profile
    @consultant = current_consultant
  end

  # POST /consultants
  # POST /consultants.json
  def create
    @consultant = Consultant.new(consultant_params)

    respond_to do |format|
      if @consultant.save
        format.html { redirect_to @consultant, notice: 'Consultor criado com sucesso.' }
        format.json { render :show, status: :created, location: @consultant }
      else
        format.html { render :new }
        format.json { render json: @consultant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consultants/1
  # PATCH/PUT /consultants/1.json
  def update
    respond_to do |format|
      
      if @consultant.update(consultant_params)
        
        @consultant.companies_consultants.each do |companies_consultants|
          companies_consultants.destroy
        end

        @consultant.companies_consultants.clear
        
        @consultant.companies.each do |company|
          companies_consultants = CompaniesConsultant.create(:company => company, :consultant => @consultant)
          @consultant.companies_consultants << companies_consultants unless @consultant.companies_consultants.include?(companies_consultants) 
        end

        format.html { redirect_to @consultant, notice: 'Consultor atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @consultant }
      else
        format.html { render :edit }
        format.json { render json: @consultant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultants/1
  # DELETE /consultants/1.json
  def destroy
    @consultant.destroy
    respond_to do |format|
      format.html { redirect_to consultants_url, notice: 'Consultor removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consultant
      @consultant = Consultant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consultant_params
      params.require(:consultant).permit(:name, :network_id, {company_ids: []})
    end
end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/views/consultants/_details.html.slim
- model_class = Consultant
p
  strong= model_class.human_attribute_name(:nome) + ':'
  br
  = @consultant.name
p
  strong= model_class.human_attribute_name(:rede) + ':'
  br
  - if @consultant.network
    = @consultant.network.name
  - else
    ' Nenhuma
p
  h3= model_class.human_attribute_name(:empresas)
  - if @consultant.companies_consultants.empty?
    ' Nenhuma empresa associada
  - else
    table.table.table-hover
      thead
        tr
          th = model_class.human_attribute_name(:nome)
          th = model_class.human_attribute_name(:email)
          th = model_class.human_attribute_name(:associada_em)
      tbody
        - @consultant.companies_consultants.each do |companyconsultant|
          tr
            td = companyconsultant.company.name
            td = companyconsultant.company.email
            td = l companyconsultant.created_at, :format => :short

app/views/consultants/_form.html.slim
= form_for @consultant, html: { class: "form form-horizontal consultant" } do |f|
  .form-group
    = f.label :nome, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, :class => 'form-control'
    = f.error_span(:name)
  .form-group
    = f.label :rede, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.collection_select :network_id, Network.all, :id, :name, { prompt: true }, { :class => 'form-control' }
    = f.error_span(:network_id)
  .form-group
    h3= Consultant.human_attribute_name(:empresas_associadas)
    .col-lg-10
      = f.collection_check_boxes(:company_ids, Company.all, :id, :name )
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit t("helpers.links.save"), :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), consultants_path, :class => 'btn'

app/views/consultants/edit.html.slim
- model_class = Consultant
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.human_attribute_name(:consultor)
= render :partial => "form"

app/views/consultants/index.html.slim
- model_class = Consultant
.page-header
  h1=t '.title', :default => model_class.human_attribute_name(:consultores)
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:nome)
      th= model_class.human_attribute_name(:rede)
      th= model_class.human_attribute_name(:criado_em)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @consultants.each do |consultant|
      tr
        td= link_to consultant.name, consultant_path(consultant)
        td
          - if consultant.network?
            = consultant.network.name
          - else
            ' Nenhuma
        td=l consultant.created_at, :format => :short
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_consultant_path(consultant), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), consultant_path(consultant), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/consultants/new.html.slim
- model_class = Consultant
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.human_attribute_name(:consultor)
= render :partial => "form"

app/views/consultants/profile.html.slim
- content_for :header do
  li= link_to "Desconectar", destroy_consultant_session_path, :method => :delete

- model_class = Consultant
.page-header
  h1
    ' Bem Vindo Consultor
    = @consultant.name

= render :partial => "details"

app/views/consultants/show.html.slim
- model_class = Consultant
.page-header
  h1=t '.title', :default => model_class.human_attribute_name(:consultor)

= render :partial => "details"

= link_to t('.back', :default => t("helpers.links.back")), consultants_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_consultant_path(@consultant), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), consultant_path(@consultant), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'