config/routes.rb
Rails.application.routes.draw do

  devise_for :networks, :consultants, :companies, :admins

  scope '/admin' do
    resources :companies, :consultants, :networks
  end

  get 'admins/index'

  get 'consultants/profile'

  get 'networks/profile'

  get 'companies/profile'

  root to: 'index#index'

end

app/models/network.rb
class Network
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :consultants

  field :name,              type: String, default: ""

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController
  layout "admin", except: [:profile]

  before_action :authenticate_network!, only: [:profile]
  before_action :authenticate_admin!, except: [:profile]
  before_action :set_network, only: [:show, :edit, :update, :destroy]

  # GET /networks
  # GET /networks.json
  def index
    @networks = Network.all
  end

  # GET /networks/1
  # GET /networks/1.json
  def show
  end

  # GET /networks/new
  def new
    @network = Network.new
  end

  # GET /networks/1/edit
  def edit
  end

  # GET /network/profile
  def profile
    @network = current_network
  end

  # POST /networks
  # POST /networks.json
  def create
    @network = Network.new(network_params)

    respond_to do |format|
      if @network.save
        format.html { redirect_to @network, notice: 'Rede criada com sucesso.' }
        format.json { render :show, status: :created, location: @network }
      else
        format.html { render :new }
        format.json { render json: @network.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /networks/1
  # PATCH/PUT /networks/1.json
  def update
    respond_to do |format|
      if @network.update(network_params)
        format.html { redirect_to @network, notice: 'Rede atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @network }
      else
        format.html { render :edit }
        format.json { render json: @network.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /networks/1
  # DELETE /networks/1.json
  def destroy
    @network.destroy
    respond_to do |format|
      format.html { redirect_to networks_url, notice: 'Rede removida com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_network
      @network = Network.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def network_params
      params.require(:network).permit(:name)
    end
end

app/helpers/networks_helper.rb
module NetworksHelper
end

app/views/networks/_details.html.slim
- model_class = Network
p
  strong= model_class.human_attribute_name(:nome) + ':'
  br
  = @network.name

p
  strong= model_class.human_attribute_name(:email) + ':'
  br
  = @network.email

p
  strong= model_class.human_attribute_name(:consultores_afiliados) + ':'
  br
  = @network.consultants.size

p
  h3= model_class.human_attribute_name(:consultores)
  - if @network.consultants.empty?
    ' Nenhum consultor afiliado
  - else
    #consultants.panel-group aria-multiselectable="true" role="tablist"
    - @network.consultants.each do |consultant|
      .panel.panel-default
        .panel-heading role="tab" id="heading_#{consultant.id}"
          h4.panel-title
            a aria-controls="#collapse_#{consultant.id}" aria-expanded="true" data-parent="#consultants" data-toggle="collapse" href="#collapse_#{consultant.id}"
              = consultant.name
        .panel-collapse.collapse aria-labelledby="heading_#{consultant.id}" role="tabpanel" id="collapse_#{consultant.id}"
          .panel-body
            p
              strong= model_class.human_attribute_name(:afiliado_em) + ':'
              br
              = l consultant.updated_at, :format => :short

            h4 = model_class.human_attribute_name(:empresas_associadas)
            - if consultant.companies_consultants.empty?
              ' Nenhuma empresa associada
            - else
              table.table.table-hover
                thead
                  tr
                    th
                      = model_class.human_attribute_name(:nome)
                    th
                      = model_class.human_attribute_name(:associada_em)
                tbody
                  - consultant.companies_consultants.each do |companyconsultant|
                    tr
                      td = companyconsultant.company.name
                      td = l companyconsultant.created_at, :format => :short

app/views/networks/_form.html.slim
= form_for @network, html: { class: "form form-horizontal network" } do |f|
  .form-group
    = f.label :nome, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, :class => 'form-control'
    = f.error_span(:name)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit t("helpers.links.save"), :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), networks_path, :class => 'btn'

app/views/networks/edit.html.slim
- model_class = Network
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.human_attribute_name(:redes)
= render :partial => "form"

app/views/networks/index.html.slim
- model_class = Network
.page-header
  h1=t '.title', :default => model_class.human_attribute_name(:redes)
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:nome)
      th= model_class.human_attribute_name(:consultores)
      th= model_class.human_attribute_name(:criado_em)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @networks.each do |network|
      tr
        td= link_to network.name, network_path(network)
        td= network.consultants.size
        td=l network.created_at, :format => :short
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_network_path(network), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), network_path(network), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/networks/new.html.slim
- model_class = Network
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.human_attribute_name(:rede)
= render :partial => "form"

app/views/networks/profile.html.slim
- content_for :header do
  li= link_to "Desconectar", destroy_network_session_path, :method => :delete

- model_class = Network
.page-header
  h1
    ' Bem Vinda Rede
    = @network.name

= render :partial => "details"

app/views/networks/show.html.slim
- model_class = Network
.page-header
  h1=t '.title', :default => model_class.human_attribute_name(:rede)

= render :partial => "details"

= link_to t('.back', :default => t("helpers.links.back")), networks_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_network_path(@network), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), network_path(@network), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'