config/routes.rb
Rails.application.routes.draw do

  devise_for :networks, :consultants, :companies, :admins

  scope '/admin' do
    resources :companies, :consultants, :networks
  end

  get 'admins/index'

  get 'consultants/profile'

  get 'networks/profile'

  get 'companies/profile'

  root to: 'index#index'

end

app/models/company.rb
class Company
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :consultants
  has_many :companies_consultants

  field :name,              type: String, default: ""

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  layout "admin", except: [:profile]

  before_action :authenticate_company!, only: [:profile]
  before_action :authenticate_admin!, except: [:profile]
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # GET /companies/profile
  def profile
    @company = current_company
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Empresa criada com sucesso.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Empresa atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Empresa removida com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_details.html.slim
-model_class = Company
p
  strong= model_class.human_attribute_name(:nome) + ':'
  br
  = @company.name
p
  h3= model_class.human_attribute_name(:consultores)
  - if @company.companies_consultants.empty?
    ' Nenhum consultor associado
  - else
    table.table.table-hover
      thead
        tr
          th
            = model_class.human_attribute_name(:nome)
          th
            = model_class.human_attribute_name(:email)
          th
            = model_class.human_attribute_name(:associada_em)
      tbody
        - @company.companies_consultants.each do |companyconsultant|
          tr
            td = companyconsultant.consultant.name
            td = companyconsultant.consultant.email
            td = l companyconsultant.created_at, :format => :short
  br

app/views/companies/_form.html.slim
= form_for @company, html: { class: "form form-horizontal company" } do |f|
  .form-group
    = f.label :nome, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, :class => 'form-control'
    = f.error_span(:name)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit t("helpers.links.save"), :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), companies_path, :class => 'btn'

app/views/companies/edit.html.slim
- model_class = Company
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.human_attribute_name(:empresa)
= render :partial => "form"

app/views/companies/index.html.slim
- model_class = Company
.page-header
  h1=t '.title', :default => model_class.human_attribute_name(:empresas)
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:nome)
      th= model_class.human_attribute_name(:criado_em)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @companies.each do |company|
      tr
        td= link_to company.name, company_path(company)
        td=l company.created_at, :format => :short
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_company_path(company), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), company_path(company), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/companies/new.html.slim
- model_class = Company
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.human_attribute_name(:empresa)
= render :partial => "form"

app/views/companies/profile.html.slim
- content_for :header do
  li= link_to "Desconectar", destroy_company_session_path, :method => :delete

- model_class = Company
.page-header
  h1
    ' Bem Vinda Empresa
    = @company.name

= render :partial => "details"

app/views/companies/show.html.slim
- model_class = Company
.page-header
  h1=t '.title', :default => model_class.human_attribute_name(:empresa)

= render :partial => "details"

= link_to t('.back', :default => t("helpers.links.back")), companies_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_company_path(@company), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), company_path(@company), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'